### PR TITLE
T30972 Fix restrict apps selector in gnome-initial-setup

### PR DESCRIPTION
**Pull request by pwithnall**
Trivial backport of the 5 commits from https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/92.

https://phabricator.endlessm.com/T30972

### CODE REVIEW

**Comment by mwleeds** [comment]
LGTM except that the CI failed:
```
1/3 app-filter     OK             0.17s
2/3 session-limits TIMEOUT        30.01s
3/3 pam_malcontent OK             0.01s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   
```

**Comment by mwleeds** [comment]
Probably the timeout is due to existing flakiness not introduced by this code, and none of the commits upstream that we don't have downstream seem relevant, but hard to be sure.

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by pwithnall** [comment]
Succeeded on the second retry, so I think it’s the same test timeout problem we’ve had before with malcontent, rather than anything introduced by this MR. Merging, thanks for the revie

**Pull request merged**
