### PR TITLE
libmalcontent-ui: Remove eos-link-* special handling

### PR DESCRIPTION
**Pull request by andrunko**
We are removing all web links from the OS, let's remove the special handling here also.

Depends on whether we are also dropping image personalities' specific web links - see endlessm/eos-image-builder#975.

https://phabricator.endlessm.com/T31560

### CODE REVIEW

**Review by pwithnall — APPROVED** [review]
LGTM iff https://github.com/endlessm/eos-image-builder/pull/975 is merged.

This code is actually also in malcontent upstream. I’ll drop it there if/when this is merged.

**Comment by wjt** [comment]
I think we can get rid of this independently of the other decisions because, these links are not Flatpaks, so they'll be hidden anyway. (Or perhaps I'm missing something?)

**Comment by andrunko** [comment]
> LGTM iff [endlessm/eos-image-builder#975](https://github.com/endlessm/eos-image-builder/pull/975) is merged.
> 
> This code is actually also in malcontent upstream. I’ll drop it there if/when this is merged.

@pwithnall Thanks, do you want me to prep an upstream patch or are you on it?

**Comment by pwithnall** [comment]
Done and released earlier today: https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/116 :)

**Pull request merged**
